name = "steinbrueck.io"
license = "MIT"
licenselink = "https://github.com/steinbrueckri/steinbrueckri.github.io/blob/master/LICENSE"
description = "Theme for steinbrueck.io"
homepage = "https://steinbrueck.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Richard Steinbrueck"
  homepage = "steinbrueck.io"
