name: Build and Deploy to Netlify
on:
  push:
  pull_request:
    types: [opened, synchronize]
env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to DEV
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './public'
          timeout-minutes: 1

      - name: Deploy to PROD
        if: github.ref == 'refs/heads/master'
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './public'
          production-deploy: 'true'
          timeout-minutes: 1